name: $CONTAINER_APP_NAME
location: eastus
resourceGroup: $RESOURCE_GROUP
environment: default

identity:
  type: UserAssigned
  userAssignedIdentities:
     "/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.ManagedIdentity/userAssignedIdentities/llm-app-user": {}
  
properties:
  configuration: 
    ingress:
        external: false # Internal access only
        targetPort: 8000  # Port exposed for the main application
        transport: auto
        allowInsecure: false
        traffic:
          - latestRevision: true
            weight: 100  # 100% traffic to the latest revision of the main app  
    identitySettings: 
      - identity: "/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.ManagedIdentity/userAssignedIdentities/llm-app-user"
        lifecycle: Main
  template:
    containers:
      - image: $ACR_NAME.azurecr.io/$IMAGE_OTELCOL_NAME:$IMAGE_TAG
        name: otelcol
        ports:
          - containerPort: 4317  # Default OTLP gRPC port
        resources:
          cpu: "0.5"
          memory: "1.0Gi"
        env:
          - name: APPLICATIONINSIGHTS_CONNECTION_STRING
            value: $APPLICATIONINSIGHTS_CONNECTION_STRING
        
      - image: $ACR_NAME.azurecr.io/$IMAGE_LLMAPP_NAME:$IMAGE_TAG
        name: sk-financial-analyst
        ports:
          - containerPort: 8000
        probes:
          - type: Liveness
            httpGet:
              path: "/"
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
        resources:
          cpu: "1.0"            # Allocate 1 CPU
          memory: "2.0Gi"  

    scale:
      minReplicas: 1
      maxReplicas: 2
      rules:
      - name: httpscalingrule
        custom:
          type: http
          metadata:
            concurrentRequests: '50'