properties:
  template:
    containers:
      - image: llmappcontainerregistry.azurecr.io/opentelemetry-collector-contrib:aac27575dc09db8f9c9dd5b4362c707f70f8e31c
        name: otelcol
      - image: llmappcontainerregistry.azurecr.io/deployments-sk-financial-analyst-app:aac27575dc09db8f9c9dd5b4362c707f70f8e31c
        name: sk-financial-analyst-app