name: $CONTAINER_APP_NAME
location: eastus
resourceGroup: $RESOURCE_GROUP
environment: default

identity:
  userAssignedIdentities:
     "/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.ManagedIdentity/userAssignedIdentities/llm-app-user": {}
  type: UserAssigned
properties:
  configuration: 
    ingress:
        external: true
        targetPort: 8000  # Main application port
        transport: auto
        allowInsecure: false
        traffic:
          - latestRevision: true
            weight: 100
    identitySettings: 
      - identity: "/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.ManagedIdentity/userAssignedIdentities/llm-app-user",
        lifecycle: Main
  template:
    containers:
      - image: $ACR_NAME.azurecr.io/$IMAGE_OTELCOL_NAME:ac9664714c87e153fce0c92f61a8271e99425c9a
        name: otelcol
        ports:
          - containerPort: 4317  # Default OTLP gRPC port
        resources:
          cpu: "0.5"
          memory: "512Mi"
        
      - image: $ACR_NAME.azurecr.io/$IMAGE_LLMAPP_NAME:$IMAGE_TAG
        name: sk-financial-analyst
        ports:
          - containerPort: 8000
        probes:
        - type: Liveness
          httpGet:
            path: "/"
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        initContainers:
        - image: $ACR_NAME.azurecr.io/$IMAGE_LLMAPP_NAME:$IMAGE_TAG
          name: sk-financial-analyst
          resources:
            cpu: 500m
            memory: 512Mi
          command:
          - "/bin/sh"
    scale:
      minReplicas: 1
      maxReplicas: 2
      rules:
      - name: httpscalingrule
        custom:
          type: http
          metadata:
            concurrentRequests: '50'