name: $CONTAINER_APP_NAME
location: eastus
resourceGroup: $RESOURCE_GROUP
environment: default

identity:
  userAssignedIdentities:
    "/subscriptions/f032cc8b-09ae-4d12-b362-cc4ec307fd97/resourceGroups/MC_mlops-semantic-kernel_mlops-sk-aks_eastus2/providers/Microsoft.ManagedIdentity/userAssignedIdentities/azurekeyvaultsecretsprovider-mlops-sk-aks": {}
  type: UserAssigned
properties:
  template:
    containers:
      - image: $ACR_NAME.azurecr.io/$IMAGE_OTELCOL_NAME:$IMAGE_TAG
        name: otelcol
        
      - image: $ACR_NAME.azurecr.io/$IMAGE_LLMAPP_NAME:$IMAGE_TAG
        name: sk-financial-analyst-app
        probes:
        - type: Liveness
          httpGet:
            path: "/"
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 3
        initContainers:
        - image: $ACR_NAME.azurecr.io/$IMAGE_LLMAPP_NAME:$IMAGE_TAG
          name: sk-financial-analyst-app
          env: 
            - name: AZURE_CLIENT_ID
              value: ${AZURE_CLIENT_ID}
            - name: AZURE_TENANT_ID
              value: ${AZURE_TENANT_ID}
          resources:
            cpu: 500m
            memory: 512Mi
          command:
          - "/bin/sh"
        scale:
          minReplicas: 1
          maxReplicas: 2
          rules:
          - name: httpscalingrule
            custom:
              type: http
              metadata:
                concurrentRequests: '50'