properties:
  template:
    containers:
      - image: llmappcontainerregistry.azurecr.io/opentelemetry-collector-contrib:${{ env.GITHUB_SHA }}
        name: otelcol
      - image: llmappcontainerregistry.azurecr.io/deployments-sk-financial-analyst-app:${{ env.GITHUB_SHA }}
        name: sk-financial-analyst-app