name: $CONTAINER_APP_NAME
location: eastus
resourceGroup: $RESOURCE_GROUP
environment: default

identity:
  userAssignedIdentities:
     "/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.ManagedIdentity/userAssignedIdentities/llm-app-user": {}
  type: UserAssigned
properties:
   configuration: {
    identitySettings: [
      { 
        identity: "/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.ManagedIdentity/userAssignedIdentities/llm-app-user",
        lifecycle: "Main"
      }
    ]
   }
   template:
    containers:
      - image: $ACR_NAME.azurecr.io/$IMAGE_OTELCOL_NAME:ac9664714c87e153fce0c92f61a8271e99425c9a
        name: otelcol
        
      - image: $ACR_NAME.azurecr.io/$IMAGE_LLMAPP_NAME:$IMAGE_TAG
        name: sk-financial-analyst
        probes:
        - type: Liveness
          httpGet:
            path: "/"
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 3
        initContainers:
        - image: $ACR_NAME.azurecr.io/$IMAGE_LLMAPP_NAME:$IMAGE_TAG
          name: sk-financial-analyst
          resources:
            cpu: 500m
            memory: 512Mi
          command:
          - "/bin/sh"
        scale:
          minReplicas: 1
          maxReplicas: 2
          rules:
          - name: httpscalingrule
            custom:
              type: http
              metadata:
                concurrentRequests: '50'