exclude: '.azureml|.devcontainer|.github|.vscode|junit/*.xml'

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          # - id: check-yaml
          #- id: check-json
          - id: detect-private-key
          - id: check-merge-conflict
    - repo: https://github.com/psf/black
      rev: 24.4.2 # Replace by any tag/version: https://github.com/psf/black/tags
      hooks:
          - id: black
            language_version: python3 # Should be a command that runs python3.6+
            args:
                - "--line-length=120"
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: flake8
            args:
              - "--max-line-length=120"
    # Temporary disable this since it gets stuck when updating env
    # - repo: https://github.com/streetsidesoftware/cspell-cli
    #   rev: v7.3.0
    #   hooks:
    #   - id: cspell
    #     args: ['--config', '.cspell.json', "--no-must-find-files"]
    - repo: https://github.com/pycqa/isort
      rev: 5.13.2
      hooks:
        - id: isort
          # stages: [commit]
          name: isort-python
          # Use black profile for isort to avoid conflicts
          # see https://github.com/PyCQA/isort/issues/1518
          args: ["--profile", "black", --line-length=120]
    # - repo: https://github.com/pre-commit/mirrors-eslint
    #   rev: '' # Use the desired ESLint version
    #   hooks:
    #     - id: eslint
    #       files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
    #       types: [file]
    #       additional_dependencies:
    #               -   eslint-plugin-react@6.10.3
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "v4.0.0-alpha.8" # Use the sha or tag you want to point at
      hooks:
        - id: prettier
          types_or: [css, ts, tsx, json]
          additional_dependencies:
                  -   prettier@2.1.2
                  -   '@prettier/plugin-xml@0.12.0'
