networks:
  default:
    driver: bridge

services:
  # OpenTelemetry Collector
  otelcol:
    image: "otel/opentelemetry-collector-contrib:latest"
    deploy:
      resources:
        limits:
          memory: 512M
    restart: always
    command: [ "--config=/etc/otelcol-config.yml" ]
    volumes:
      - ./otel-config-azuremonitor.yaml:/etc/otelcol-config.yml
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318"
    environment:
      - APPLICATIONINSIGHTS_CONNECTION_STRING
    networks:
      - default

  sk-financial-analyst-app:
    build:
      context: ../..
      dockerfile: ./common/deployments/Dockerfile
      args:
        OTEL_COLLECTOR_HOST: "otelcol"
        OTEL_COLLECTOR_PORT_GRPC: "4317"
        OTEL_COLLECTOR_PORT_HTTP: "4318"
        OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED: "true"
        NEWS_ANALYST_MODEL_NAME: "gpt-4o"
        FINANCIAL_ANALYST_MODEL_NAME: "gpt-4o"
        REPORT_GENERATOR_MODEL_NAME: "gpt-4o"
        KEY_VAULT_URL: "https://llm-app-keyvault.vault.azure.net/"
        OTEL_SERVICE_NAME: "sk-financial-analyst-dev"
        OTEL_LOGS_EXPORTER: "otlp"
        OTEL_TRACES_EXPORTER: "otlp"
        OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
        OTEL_EXPORTER_OTLP_INSECURE: "true"
        OTEL_LOG_LEVEL: "INFO"
        OTEL_RESOURCE_ATTRIBUTES: "service.name=sk-financial-analyst-dev"
        AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
        AZURE_TENANT_ID: ${AZURE_TENANT_ID}
        OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://${OTEL_COLLECTOR_HOST}:${OTEL_COLLECTOR_PORT_HTTP}/v1/traces
        OTEL_EXPORTER_OTLP_ENDPOINT: http://${OTEL_COLLECTOR_HOST}:${OTEL_COLLECTOR_PORT_GRPC}

    container_name: sk-financial-analyst-app
    deploy:
      resources:
        limits:
          memory: 500M
    restart: unless-stopped
    # environment:
    #   - OTEL_COLLECTOR_HOST="otelcol"
    #   - OTEL_COLLECTOR_PORT_GRPC="4317"
    #   - OTEL_COLLECTOR_PORT_HTTP="4318"
    #   - OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED="true"
    #   - NEWS_ANALYST_MODEL_NAME="gpt-4o"
    #   - FINANCIAL_ANALYST_MODEL_NAME="gpt-4o"
    #   - REPORT_GENERATOR_MODEL_NAME="gpt-4o"
    #   - KEY_VAULT_URL="https://llm-app-keyvault.vault.azure.net/"
    #   - OTEL_SERVICE_NAME="sk-financial-analyst-dev"
    #   - OTEL_LOGS_EXPORTER="otlp"
    #   - OTEL_TRACES_EXPORTER="otlp"
    #   - OTEL_EXPORTER_OTLP_PROTOCOL="grpc"
    #   - OTEL_EXPORTER_OTLP_INSECURE="true"
    #   - OTEL_LOG_LEVEL="INFO"
    #   - OTEL_RESOURCE_ATTRIBUTES="service.name=sk-financial-analyst-dev"
    #   - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
    #   - AZURE_TENANT_ID=${AZURE_TENANT_ID}
    #   - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://${OTEL_COLLECTOR_HOST}:${OTEL_COLLECTOR_PORT_HTTP}/v1/traces
    #   - OTEL_EXPORTER_OTLP_ENDPOINT=http://${OTEL_COLLECTOR_HOST}:${OTEL_COLLECTOR_PORT_GRPC}

    networks:
      - default
    depends_on:
      otelcol:
        condition: service_started
