services:
  # OpenTelemetry Collector
  otelcol:
    image: ${COLLECTOR_CONTRIB_IMAGE}
    container_name: otel-col
    deploy:
      resources:
        limits:
          memory: 125M
    restart: unless-stopped
    command: [ "--config=/etc/otelcol-config.yml" ]
    volumes:
      - ./otel-config-azuremonitor.yaml:/etc/otelcol-config.yml
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318"
    environment:
      - APPLICATIONINSIGHTS_CONNECTION_STRING

  # sk-financial-analyst-app:
  #   build:
  #     context: ../..
  #     dockerfile: ./sk_financial_analyst/deployment/Dockerfile
  #   container_name: sk-financial-analyst-app
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 500M
  #   restart: unless-stopped
  #   env_file:
  #     ../../.env
  #   environment:
  #     - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
  #   logging: *logging
