name: Build Csharp Validation Workflow

on:
  workflow_call:

env:
  DOTNET_VERSION: "8.0.10"

jobs:
  run-unit-tests-csharp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore Dependencies
        run: dotnet restore

      - name: Lint C# Code
        run: dotnet format --check

      - name: Build Project
        run: dotnet build --no-restore --configuration Release

      - name: Run Unit Tests
        run: dotnet test --no-build --configuration Release --logger "trx;LogFileName=test-results.trx"

      - name: Publish Test Results
        uses: actions/upload-artifact@v3
        with:
          name: csharp-test-results
          path: "**/TestResults/*.trx"