name: Build Java Validation Workflow

on:
  workflow_call:

env:
  JAVA_VERSION: "21"

jobs:
  run-unit-tests-java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Lint Java Code
        run: mvn checkstyle:check

      - name: Run Java Unit Tests
        run: mvn test

      - name: Publish Java Test Results
        uses: actions/upload-artifact@v3
        with:
          name: java-test-results
          path: "**/target/surefire-reports/*.xml"