name: Pre-build dev container image and Push to ACR

on:
    pull_request:
        branches:
        - 'main'
        paths:
        - '.github/**'
        - 'python/**'
        - 'tests/**'
        - 'evaluators/**'

env:
    IMAGE_NAME: devops_container_image
    REGISTRY: ${{ secrets.ACR_CONTAINER_REGISTRY }}.azurecr.io

permissions:
    id-token: write
    contents: read

jobs:
  build-and-push-build-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR with Azure CLI
        run: |
          az acr login --name ${{ secrets.ACR_CONTAINER_REGISTRY }} --username ${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.buildcontainer/Dockerfile 
          push: true
          no-cache: true
          tags: ${{ secrets.ACR_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
