---
    name: CI Platform Python Workflow

    on:
      push:
        branches:
          - 'main'
        paths:
          - '.github/**'
          - 'python/**'
          - 'tests/**'
          - 'evaluators/**'

    permissions:
      id-token: write
      contents: read

    jobs:
      build-and-deploy-python:
        runs-on: ubuntu-latest
        steps:
          - name: Azure login
            uses: azure/login@v2
            with:
              client-id: ${{ secrets.AZURE_CLIENT_ID }}
              tenant-id: ${{ secrets.AZURE_TENANT_ID }}
              subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
          - name: Azure CLI script
            uses: azure/cli@v2
            with:
              azcliversion: latest
              inlineScript: |
                az account show