---
    name: CI Platform Python Workflow

    on:
      push:
        branches:
          - 'otel'
        paths:
          - '.github/**'
          - 'python/**'
          - 'tests/**'
          - 'evaluators/**'

    permissions:
      id-token: write
      contents: read
    
    env:
      GITHUB_SHA: ${{ github.sha }}

    jobs:
      build-and-deploy-python:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - uses: actions/setup-python@v4
            with:
              python-version: ${{ env.PYTHON_VERSION }}

          - name: Azure login with federated credentials
            uses: azure/login@v2
            with:
              client-id: ${{ secrets.AZURE_CLIENT_ID }}
              tenant-id: ${{ secrets.AZURE_TENANT_ID }}
              subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
          - name: Azure CLI script
            uses: azure/cli@v2
            with:
              azcliversion: latest
              inlineScript: |
                az account show

          - name: Docker login ACR
            uses: Azure/docker-login@v1
            with:
              login-server: llmappcontainerregistry.azurecr.io/
              username: ${{ secrets.ACR_USERNAME }}
              password: ${{ secrets.ACR_PASSWORD }}

          - name: Build and push Docker image
            working-directory: python
            run: |
              export APPLICATIONINSIGHTS_CONNECTION_STRING=${{secrets.APPLICATIONINSIGHTS_CONNECTION_STRING}} 
              export AZURE_CLIENT_ID="077e01b1-31dc-4c39-923f-dd7988033567"
              export AZURE_TENANT_ID=${{secrets.AZURE_TENANT_ID}}
              docker compose -f common/deployments/docker-compose.yaml \
              up --build --remove-orphans --detach
              docker tag deployments-sk-financial-analyst-app:latest llmappcontainerregistry.azurecr.io/deployments-sk-financial-analyst-app:${{ github.sha }}
              docker tag otel/opentelemetry-collector-contrib:latest llmappcontainerregistry.azurecr.io/opentelemetry-collector-contrib:${{ github.sha }}
              docker push llmappcontainerregistry.azurecr.io/deployments-sk-financial-analyst-app:${{ github.sha }}
              docker push llmappcontainerregistry.azurecr.io/opentelemetry-collector-contrib:${{ github.sha }}

          - name: Set Environment Variables
            run: |
              echo "CONTAINER_APP_NAME=mlops-llm-containerapp" >> $GITHUB_ENV
              echo "RESOURCE_GROUP=mlops-llm-application" >> $GITHUB_ENV
              echo "SUBSCRIPTION_ID=$(az account show --query id -o tsv)" >> $GITHUB_ENV
              echo "ENVIRONMENT_NAME=default" >> $GITHUB_ENV
              echo "ACR_NAME=llmappcontainerregistry" >> $GITHUB_ENV
              echo "IMAGE_OTELCOL_NAME=opentelemetry-collector-contrib" >> $GITHUB_ENV 
              echo "IMAGE_LLMAPP_NAME=deployments-sk-financial-analyst-app" >> $GITHUB_ENV
              echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV
              echo MI_CLIENT_ID="077e01b1-31dc-4c39-923f-dd7988033567" >> $GITHUB_ENV
              export MI_CLIENT_ID="077e01b1-31dc-4c39-923f-dd7988033567"
              echo AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }} >> $GITHUB_ENV

          - name: Substitute Variables in YAML
            run: |
              envsubst < .github/simple-image-container-app.yaml > .github/simple-image-container-app.processed.yaml

          - name: Build and deploy Container App and Open telemetry collector
            uses: azure/container-apps-deploy-action@v1
            with:
              yamlConfigPath: .github/simple-image-container-app.processed.yaml
              acrName: ${{ env.ACR_NAME }}
              acrUsername: ${{ secrets.ACR_USERNAME }}
              acrPassword: ${{ secrets.ACR_PASSWORD }}
              containerAppName: ${{ env.CONTAINER_APP_NAME }}
              resourceGroup: ${{ env.RESOURCE_GROUP }}