---
name: PR Platform Python Workflow

on:
  workflow_call:

  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/**'
      - 'python/**'
      - 'tests/**'
      - 'evaluators/**'

permissions:
  id-token: write
  contents: read

jobs:
  build-validation-python:
    name: Build Validation Python
    uses: ./.github/workflows/build_python.yml

  run-generate-report:
    name: Run generate_report
    runs-on: ubuntu-latest
    needs: build-validation-python
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        working-directory: python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get secret from Key Vault
        run: |
          az keyvault secret show --name "AOAI-BASE-ENDPOINT" --vault-name "llm-app-keyvault" --query "value"

      - name: Run generate_report
        working-directory: python
        env:
          KEY_VAULT_URL: "https://llm-app-keyvault.vault.azure.net/"
        run: |
          python -m sk_financial_analyst.executors.single_item_executor