---
    name: PR Platform Python Workflow

    on:
      workflow_call:

      pull_request:
        branches:
          - 'main'
        paths:
          - '.github/**'
          - 'python/**'
          - 'tests/**'
          - 'evaluators/**'

    permissions:
      id-token: write
      contents: read

    jobs:
      build-validation-python:
        name: Build Validation Python
        uses: ./.github/workflows/build_python.yml

      run-generate-eval-report:
        name: Run generate_eval_report
        needs: build-validation-python
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: '3.12'

          - name: Install dependencies
            working-directory: python
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

          - name: Azure login
            uses: azure/login@v2
            with:
              client-id: ${{ secrets.AZURE_CLIENT_ID }}
              tenant-id: ${{ secrets.AZURE_TENANT_ID }}
              subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

          - name: Run generate_report
            working-directory: python
            env:
              KEY_VAULT_URL: ${{ vars.KEY_VAULT_URL }}
              NEWS_ANALYST_MODEL_NAME: ${{ vars.NEWS_ANALYST_MODEL_NAME }}
              FINANCIAL_ANALYST_MODEL_NAME: ${{ vars.FINANCIAL_ANALYST_MODEL_NAME }}
              REPORT_GENERATOR_MODEL_NAME: ${{ vars.REPORT_GENERATOR_MODEL_NAME }}
            run: |
              python -u -m sk_financial_analyst.executors.single_item_executor --logging_enabled